CUDA_VISIBLE_DEVICES=0  bin/train.sh config/conll05-lisa.conf --hparams batch_size=64 --save_dir chinese_new >> chinese_new_model
CUDA_VISIBLE_DEVICES=0  bin/train.sh config/conll05-lisa.conf --hparams batch_size=64 --save_dir chinese_new >> chinese_new_model
CUDA_VISIBLE_DEVICES=0  bin/train.sh config/conll05-lisa.conf --hparams batch_size=64 --save_dir chinese_new >> chinese_new_model
CUDA_VISIBLE_DEVICES=0  bin/train.sh config/conll05-lisa.conf --hparams batch_size=64 --save_dir chinese_new >> chinese_new_model
CUDA_VISIBLE_DEVICES=0  bin/train.sh config/conll05-lisa.conf --hparams batch_size=64 --save_dir chinese_new >> chinese_new_model
CUDA_VISIBLE_DEVICES=0  bin/train.sh config/conll05-lisa.conf --hparams batch_size=64 --save_dir chinese_new >> chinese_new_model
CUDA_VISIBLE_DEVICES=0  bin/train.sh config/conll05-lisa.conf --hparams batch_size=64 --save_dir chinese_new >> chinese_new_model
CUDA_VISIBLE_DEVICES=0  bin/train.sh config/conll05-lisa.conf --hparams batch_size=64 --save_dir chinese_new >> chinese_new_model
CUDA_VISIBLE_DEVICES=0  bin/train.sh config/conll05-lisa.conf --hparams batch_size=64 --save_dir chinese_new >> chinese_new_model
CUDA_VISIBLE_DEVICES=0  bin/train.sh config/conll05-lisa.conf --hparams batch_size=64 --save_dir chinese_new >> chinese_new_model
CUDA_VISIBLE_DEVICES=0  bin/train.sh config/conll05-lisa.conf --hparams batch_size=64 --save_dir chinese_new >> chinese_new_model
CUDA_VISIBLE_DEVICES=0  bin/train.sh config/conll05-lisa.conf --hparams batch_size=64 --save_dir chinese_new >> chinese_new_model
CUDA_VISIBLE_DEVICES=0  bin/train.sh config/conll05-lisa.conf --hparams batch_size=64 --save_dir chinese_new >> chinese_new_model
CUDA_VISIBLE_DEVICES=0  bin/train.sh config/conll05-lisa.conf --hparams batch_size=64 --save_dir chinese_new >> chinese_new_model
CUDA_VISIBLE_DEVICES=0  bin/train.sh config/conll05-lisa.conf --hparams batch_size=64 --save_dir chinese_new >> chinese_new_model
CUDA_VISIBLE_DEVICES=0  bin/train.sh config/conll05-lisa.conf --hparams batch_size=64 --save_dir chinese_new >> chinese_new_model
CUDA_VISIBLE_DEVICES=0  bin/train.sh config/conll05-lisa.conf --hparams batch_size=64 --save_dir chinese_new >> chinese_new_model
CUDA_VISIBLE_DEVICES=0  bin/train.sh config/conll05-lisa.conf --hparams batch_size=64 --save_dir chinese_new >> chinese_new_model
CUDA_VISIBLE_DEVICES=0  bin/train.sh config/conll05-lisa.conf --hparams batch_size=64 --save_dir chinese_new >> chinese_new_model
CUDA_VISIBLE_DEVICES=0  bin/train.sh config/conll05-lisa.conf --hparams batch_size=64 --save_dir chinese_new >> chinese_new_model
CUDA_VISIBLE_DEVICES=0  bin/train.sh config/conll05-lisa.conf --hparams batch_size=64 --save_dir chinese_new >> chinese_new_model
CUDA_VISIBLE_DEVICES=0  bin/train.sh config/conll05-lisa.conf --hparams batch_size=64 --save_dir chinese_new >> chinese_new_model
